export const pages = [
  { name: "Home", path: "/", aliases: ["Main", "Homepage"] },
  { name: "About", path: "/about", aliases: ["About Us", "Info"] },
  { name: "Board", path: "/board", aliases: ["Executive Team", "Leadership", "Officers", "E board", "E-Board", "President"] },
  {
    name: "Past Board",
    path: "/past-board",
    aliases: ["Executive Team", "Leadership", "Officers", "E board", "E-Board", "President", "Past leadership", "Past officers"],
  },
  { name: "Sponsors", path: "/sponsors", aliases: ["Partners", "Supporters", "Sponsorships"] },
  { name: "Events", path: "/events", aliases: ["Meetings", "Workshops", "Slides"] },
  { name: "Gallery", path: "/gallery", aliases: ["Photos", "Images", "Media"] },
  { name: "Blogs", path: "/blogs", aliases: ["Articles", "News", "Posts"] },
  { name: "Programs", path: "/programs", aliases: ["Interns", "Gator Rover", "SWEET", "Sports"] },
  { name: "Interns", path: "/interns", aliases: ["SASE Interns", "Internships"] },
  { name: "Mentor Mentee", path: "/mentor-mentee", aliases: ["Mentor", "Mentee"] },
  { name: "Gator Rover", path: "/set", aliases: ["SET", "SASE Engineering Team", "Engineering Team"] },
  {
    name: "SWEET",
    path: "/webdev",
    aliases: ["Web Dev", "Web Development", "Website Team", "Website", "Reactjs", "Computer Science", "Software Engineering"],
  },
  { name: "Sports", path: "/sports", aliases: ["SASE Sports", "Athletics", "Recreational", "Volleyball", "Badminton", "Soccer", "Flag Football"] },
  {
    name: "Projects",
    path: "/projects",
    aliases: ["SASE Projects", "Technical Projects", "Research", "Discord Bot", "NAS", "Automation"],
  },
  { name: "SASEHacks", path: "/sasehacks", aliases: ["Hackathon", "SASE Hacks"] },
  { name: "Community Outreach", path: "/community-outreach", aliases: ["Outreach", "Volunteering", "Service"] },
  { name: "SASE PCR", path: "/sase-pcr", aliases: ["PCR"] },
];
