import { imageUrls } from "@assets/imageUrls";

const boardInfo = [
  {
    section: "Executive Board",
    members: [
      {
        name: "Michael Hemingway",
        role: "President",
        image: imageUrls["MichaelHemingway-26.jpg"],
        major: "3rd Year Electrical Engineering",
        contact: "ufsase.president@gmail.com",
        linkedin: "https://www.linkedin.com/in/michael-hemingway-uf/",
        description: "",
      },
      {
        name: "Logan Thompson",
        role: "Internal Vice President",
        image: imageUrls["LoganThompson-26.jpg"],
        major: "3rd Year Nuclear Engineering",
        contact: "ufsase.vp@gmail.com",
        linkedin: "https://www.linkedin.com/in/loganthompson3/",
        description: "",
      },
      {
        name: "Kayla Chen",
        role: "External Vice President",
        image: imageUrls["KaylaChen-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "ufsase.evp@gmail.com",
        linkedin: "https://www.linkedin.com/in/kaylachenn/",
        description: "",
      },
      {
        name: "Pryanna Pradhan",
        role: "Treasurer",
        image: imageUrls["PryannaPradhan-26.jpg"],
        major: "3rd Year Data Science",
        contact: "ufsase.treasurer@gmail.com",
        linkedin: "https://www.linkedin.com/in/pryanna-pradhan/",
        description: "",
      },
      {
        name: "Sharlene Kho",
        role: "Secretary",
        image: imageUrls["SharleneKho-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "ufsase.secretary@gmail.com",
        linkedin: "https://www.linkedin.com/in/sharlenekho/",
        description: "",
      },
      {
        name: "Savin Karki",
        role: "Public Relations",
        image: imageUrls["SavinKarki-26.jpg"],
        major: "3rd Year Health Science",
        contact: "ufsase.pr@gmail.com",
        linkedin: "https://www.linkedin.com/in/savin-karki/",
        description: "",
      },
    ],
  },
  {
    section: "Chair Board",
    members: [
      {
        name: "Mia Fu",
        role: "Advancement",
        image: imageUrls["MiaFu-26.jpg"],
        major: "2nd Year Mechanical Engineering",
        contact: "ufsase.advancement@gmail.com",
        linkedin: "https://www.linkedin.com/in/miafu07/",
        description: "",
      },
      {
        name: "Maryanne Anderson Lee",
        role: "Community Outreach",
        image: imageUrls["MaryanneAndersonLee-26.jpg"],
        major: "4th Year Mechanical Engineering",
        contact: "ufsase.precollegiate@gmail.com",
        linkedin: "https://www.linkedin.com/in/maryanneandersonlee/",
        description: "",
      },
      {
        name: "Micah Tam",
        role: "Gator Rover",
        image: imageUrls["MicahTam-26.jpg"],
        major: "4th Year Computer Science",
        contact: "ufsase.tech@gmail.com",
        linkedin: "https://www.linkedin.com/in/micahtam/",
        description: "",
      },
      {
        name: "Lauren Cugno",
        role: "Fundraising",
        image: imageUrls["LaurenCugno-26.jpg"],
        major: "2nd Year Chemical Engineering",
        contact: "ufsase.fundraising@gmail.com",
        linkedin: "https://www.linkedin.com/in/lauren-cugno/",
        description: "",
      },
      {
        name: "Yuwei Huang",
        role: "Hackathon",
        image: imageUrls["YuweiHuang-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "ufsase.hackathon@gmail.com",
        linkedin: "https://www.linkedin.com/in/yuwei-huang-/",
        description: "",
      },
      {
        name: "Sarah Mann",
        role: "Historian",
        image: imageUrls["SarahMann-26.jpg"],
        major: "3rd Year Civil Engineering",
        contact: "ufsase.historian@gmail.com",
        linkedin: "https://www.linkedin.com/in/sarahmann2025/",
        description: "",
      },
      {
        name: "Jason Li",
        role: "Multimedia",
        image: imageUrls["JasonLi-26.jpg"],
        major: "2nd Year Mechanical Engineering",
        contact: "ufsase.multimedia@gmail.com",
        linkedin: "https://www.linkedin.com/in/jasonliuf/",
        description: "",
      },
      {
        name: "Kaylee Renna",
        role: "Multimedia",
        image: imageUrls["KayleeRenna-26.jpg"],
        major: "2nd Year Digital Arts and Sciences",
        contact: "ufsase.multimedia@gmail.com",
        linkedin: "https://www.linkedin.com/in/kaylee-renna-723845349/",
        description: "",
      },
      {
        name: "Khanh Pham",
        role: "Member Involvement",
        image: imageUrls["KhanhPham-26.jpg"],
        major: "2nd Year Mechanical Engineering",
        contact: "ufsase.moc@gmail.com",
        linkedin: "https://www.linkedin.com/in/khanhmpham/",
        description: "",
      },
      {
        name: "Kathleen Wu",
        role: "Member Involvement",
        image: imageUrls["KathleenWu-26.jpg"],
        major: "3rd Year Chemical Engineering",
        contact: "ufsase.moc@gmail.com",
        linkedin: "https://www.linkedin.com/in/kathleenwu1/",
        description: "",
      },
      {
        name: "Joyce Chen",
        role: "Networking",
        image: imageUrls["JoyceChen-26.jpg"],
        major: "2nd Year Industrial & Systems Engineering",
        contact: "ufsase.alumni@gmail.com",
        linkedin: "https://www.linkedin.com/in/joyce-y-chen/",
        description: "",
      },
      {
        name: "Bryant Cao",
        role: "Projects",
        image: imageUrls["BryantCao-26.jpg"],
        major: "4th Year Industrial & Systems Engineering",
        contact: "uf.saseprojects@gmail.com",
        linkedin: "https://www.linkedin.com/in/bryant-cao/",
        description: "",
      },
      {
        name: "Jordan Kusuda",
        role: "Projects",
        image: imageUrls["JordanKusuda-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "uf.saseprojects@gmail.com",
        linkedin: "https://www.linkedin.com/in/jordankusuda/",
        description: "",
      },
      {
        name: "Sriya Boggavarapu",
        role: "SERC",
        image: imageUrls["SriyaBoggavarapu-26.jpg"],
        major: "2nd Year Electrical Engineering",
        contact: "ufsase.conference@gmail.com",
        linkedin: "https://www.linkedin.com/in/sriya-boggavarapu/",
        description: "",
      },
      {
        name: "Minh Pham",
        role: "Science",
        image: imageUrls["PhamMinh-26.jpg"],
        major: "2nd Year Biomedical Engineering",
        contact: "ufsase.science@gmail.com",
        linkedin: "https://www.linkedin.com/in/ph%E1%BA%A1m-minh-443824361/",
        description: "",
      },
      {
        name: "Saee Joshi",
        role: "Science",
        image: imageUrls["SaeeJoshi-26.jpg"],
        major: "2nd Year Microbiology & Neuroscience",
        contact: "ufsase.science@gmail.com",
        linkedin: "https://www.linkedin.com/in/saee-joshi-33abb1251/",
        description: "",
      },
      {
        name: "Sarah Zhang",
        role: "Social",
        image: imageUrls["SarahZhang-26.jpg"],
        major: "2nd Year Industrial & Systems Engineering",
        contact: "ufsase.social@gmail.com",
        linkedin: "https://www.linkedin.com/in/sarah-zhang14/",
        description: "",
      },
      {
        name: "Andrew Lo",
        role: "Sports",
        image: imageUrls["AndrewLo-26.jpg"],
        major: "3rd Year Computer Engineering",
        contact: "ufsase.sports@gmail.com",
        linkedin: "https://www.linkedin.com/in/andrew-lo-52b2301b6/",
        description: "",
      },
      {
        name: "Xiyue (Carol) Shang",
        role: "Sports",
        image: imageUrls["CarolShang-26.jpg"],
        major: "2nd Year Biotechnology",
        contact: "ufsase.sports@gmail.com",
        linkedin: "https://www.linkedin.com/in/xiyue-carol-shang/",
        description: "",
      },
      {
        name: "Jonathan Tang",
        role: "Webmaster",
        image: imageUrls["JonathanTang-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "ufsase.webmaster@gmail.com",
        linkedin: "https://www.linkedin.com/in/jonathantanguf/",
        description: "",
      },
      {
        name: "Kenzo Fukuda",
        role: "Webmaster",
        image: imageUrls["KenzoFukuda-26.jpg"],
        major: "3rd Year Computer Science",
        contact: "ufsase.webmaster@gmail.com",
        linkedin: "https://www.linkedin.com/in/kenzo-fukuda/",
        description: "",
      },
    ],
  },
];

export default boardInfo;
