const pastBoardInfo = [
  {
    section: "Executive Board",
    members: [
      {
        name: "Vincent Lin",
        role: "President",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKrVxaEURbEs4TRcWoUF2IXm7SkVeh1jfDOCKL",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Bryan Park",
        role: "Internal Vice President",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKuoyshP1qQZ4jYNG9Died5b2HW7PTrE6ofnMy",
        major: "Mechanical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Kayleen Diaz",
        role: "External Vice President",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTK8B5e2p72mngvWkRb9GKClx07EaLjcMz43UNV",
        major: "Mechanical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Gayatri Baskaran",
        role: "Treasurer",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKNXqN1w6liO0PyMnrk6QLBEUfbdSJt1ZweYGC",
        major: "Computer Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Rachel Young",
        role: "Secretary",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKnu1gWggk1mtwbg4xWloVfSsIBDdqaGNCejMH",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Kimmy Chiu",
        role: "Public Relations",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKBsdItF3ULJG6YbFtkQIHNdvnrupfCaVTR0mi",
        major: "Environmental Engineering",
        contact: " ",
        description: " ",
      },
    ],
  },
  {
    section: "Chair Board",
    members: [
      {
        name: "Amanda Jiang",
        role: "Advancement",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKBzimqP13ULJG6YbFtkQIHNdvnrupfCaVTR0m",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Chloe Bai",
        role: "Fundraising",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTK0OwNRgvfmUDLvlEFI6HpA2aq5tQX7dbR8hWr",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Helen Zou",
        role: "Historian",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKLwUB2A9MrDVyAlf08kn7JZT9PI5tC2cYxsUS",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Anna Lim",
        role: "Member Involvement",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKa621FynXYPwCL3hnGoHcRr14xNQzV28Tf9AJ",
        major: "Biochemistry & Music Performance",
        contact: " ",
        description: " ",
      },
      {
        name: "Justin Doan",
        role: "Member Involvement",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKd9rg5TsDSqyBaK2UuGLsiH3O8M6bme7QcfvE",
        major: "Environmental Engineering",
        contact: " ",
        description: " ",
      },

      {
        name: "Adriel Poon",
        role: "Multimedia",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKmBN1dHCUFt7WHBzodX0e53R9rvPmhyAOQC8M",
        major: "Computer Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Reyna Simpson",
        role: "Multimedia",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKR8kr0JYhYGDO1uAdSyaxqzpKXj8FtecmfE4V",
        major: "Material Science Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Tabitha Gottipati",
        role: "Network",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKaHQzcVnXYPwCL3hnGoHcRr14xNQzV28Tf9AJ",
        major: "Mechanical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Aahan Dwivedi",
        role: "Science",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTK1CCfHyr5SC0E6Wbrwzu71JZsf4yQnHeAI9Lq",
        major: "Physics & Math",
        contact: " ",
        description: " ",
      },
      {
        name: "Leann Tang",
        role: "Service",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKcqEYUxPpMwbOnfqEJ7TVa05IgRhUszKWGF28",
        major: "Mechanical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Sophia Dong",
        role: "Social",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKgaKPoiyXIQqdZjMrRAYFC9vhf6kpPOuLl8an",
        major: "Industrial and Systems Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Jessica Lu",
        role: "Sports Coordinator",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKZPwuvYTUK37NizSDsHEkotUuxbQI90TjAnm5",
        major: "Chemical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Alexander Lou",
        role: "Sports Coordinator",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTK3lM42vjaKwIicDGl8vTn5hBtmV0PXJLsH4eF",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
      {
        name: "Manav Sanghvi",
        role: "Technical",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKnNSalgk1mtwbg4xWloVfSsIBDdqaGNCejMH6",
        major: " ",
        contact: " ",
        description: " ",
      },
      {
        name: "Kevin Tang",
        role: "Technical",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKIGYUtTz2IJDaG589To0SN4hLYtuCq1Env6XK",
        major: "Mechanical Engineering",
        contact: " ",
        description: " ",
      },
      {
        name: "Ricky Zhang",
        role: "Webmaster",
        image: "https://moqsegbvdj.ufs.sh/f/2ipokchyMOTKrffZsdBRbEs4TRcWoUF2IXm7SkVeh1jfDOCK",
        major: "Computer Science",
        contact: " ",
        description: " ",
      },
    ],
  },
];

export default pastBoardInfo;
